# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20160804_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_userid', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='follow',
            field=models.ManyToManyField(to='photos.Follow'),
        ),
    ]
