# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0006_auto_20160804_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='follow',
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
